package main

import (
	"errors"
	"fmt"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/dynamicpb"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	defaultModulePath = "github.com/Iori372552686/GoOne"
	ssrpcOptFilePath  = "goone/options/v1/options.proto"
	ssrpcExtFullName  = "goone.options.v1.ssrpc"
)

// Generate is the Phase-A generator:
// - It DOES NOT generate pb.go (handled by protoc-gen-go).
// - It generates SSPacket RPC registration code (*goone_ssrpc.gen.go) for methods
//   annotated with option (goone.options.v1.ssrpc).
func Generate(req *pluginpb.CodeGeneratorRequest) (*pluginpb.CodeGeneratorResponse, error) {
	files := map[string]*descriptorpb.FileDescriptorProto{}
	for _, f := range req.GetProtoFile() {
		files[f.GetName()] = f
	}

	extType, extMsgDesc, err := buildSsRpcExtension(req.GetProtoFile())
	if err != nil {
		return nil, err
	}

	typeReg, err := BuildTypeRegistry(req.GetProtoFile())
	if err != nil {
		return nil, err
	}

	resp := new(pluginpb.CodeGeneratorResponse)
	resp.SupportedFeatures = proto.Uint64(uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL))

	params := parseParams(req.GetParameter())

	for _, name := range req.GetFileToGenerate() {
		fd := files[name]
		if fd == nil {
			continue
		}

		// Only generate for files that have services.
		if len(fd.GetService()) == 0 {
			continue
		}

		outName, pkgName, err := outputFileNameAndPkg(fd, name, params)
		if err != nil {
			return nil, err
		}

		curGoPkgOpt := fd.GetOptions().GetGoPackage()
		curImportPath, _ := splitGoPackage(curGoPkgOpt, fd.GetPackage())

		content, err := renderSSRPC(fd, pkgName, curImportPath, typeReg, extType, extMsgDesc)
		if err != nil {
			return nil, err
		}
		resp.File = append(resp.File, &pluginpb.CodeGeneratorResponse_File{
			Name:    &outName,
			Content: &content,
		})
	}
	return resp, nil
}

type genParams struct {
	paths  string // "import" (default) or "source_relative"
	module string
}

func parseParams(p string) genParams {
	gp := genParams{paths: "import", module: defaultModulePath}
	// protoc passes plugin parameter as comma-separated list
	for _, part := range strings.Split(p, ",") {
		part = strings.TrimSpace(part)
		if strings.HasPrefix(part, "paths=") {
			gp.paths = strings.TrimPrefix(part, "paths=")
		}
		if strings.HasPrefix(part, "module=") {
			gp.module = strings.TrimPrefix(part, "module=")
		}
	}
	return gp
}

func outputFileNameAndPkg(fd *descriptorpb.FileDescriptorProto, protoPath string, p genParams) (outName string, pkgName string, err error) {
	pkg := fd.GetPackage()
	goPkg := fd.GetOptions().GetGoPackage()
	pkgName = guessGoPkgName(goPkg, pkg)

	base := strings.TrimSuffix(filepath.Base(protoPath), filepath.Ext(protoPath))

	if p.paths == "source_relative" || goPkg == "" {
		// source_relative output next to proto file path
		outName = strings.TrimSuffix(protoPath, filepath.Ext(protoPath)) + ".goone_ssrpc.gen.go"
		return outName, pkgName, nil
	}

	// import-based output: honor go_package.
	goPkgPath := goPkg
	if i := strings.LastIndex(goPkgPath, ";"); i >= 0 {
		goPkgPath = goPkgPath[:i]
	}
	modulePrefix := strings.TrimRight(p.module, "/") + "/"
	if !strings.HasPrefix(goPkgPath, modulePrefix) {
		return "", "", fmt.Errorf("go_package must start with %q, got %q (file=%s)", modulePrefix, goPkgPath, protoPath)
	}
	relDir := strings.TrimPrefix(goPkgPath, modulePrefix)
	outName = path.Join(relDir, base+".goone_ssrpc.gen.go")
	return outName, pkgName, nil
}

func renderSSRPC(fd *descriptorpb.FileDescriptorProto, goPkgName string, curImportPath string, typeReg *TypeRegistry, extType protoreflect.ExtensionType, extMsgDesc protoreflect.MessageDescriptor) (string, error) {
	var b strings.Builder
	b.WriteString("// Code generated by protoc-gen-goone. DO NOT EDIT.\n\n")
	b.WriteString("package " + goPkgName + "\n\n")

	// We collect imports dynamically to support cross-package message types.
	ib := newImportBuilder()
	// reserve aliases used in file
	ib.usedAliases["g1_protocol"] = true
	ib.usedAliases["proto"] = true
	ib.usedAliases["cmd_handler"] = true
	ib.usedAliases["ssrpc"] = true
	ib.usedAliases["transaction"] = true

	// generate per service
	localPkg := fd.GetPackage()

	typeRef := func(fullType string) (string, string, error) {
		// If using source_relative, allow local package type names even without go_package.
		// This keeps behavior consistent with protoc-gen-go default package resolution.
		if strings.HasPrefix(strings.TrimPrefix(fullType, "."), localPkg+".") {
			localType, err := goTypeNameFromProtoType(localPkg, fullType)
			if err == nil {
				return localType, "", nil
			}
		}

		gt, ok := typeReg.Resolve(fullType)
		if !ok {
			return "", "", fmt.Errorf("cannot resolve proto type %q (did you set go_package for that file?)", fullType)
		}
		if gt.ImportPath == "" || gt.PkgName == "" {
			return "", "", fmt.Errorf("invalid go_package for proto type %q (importPath=%q pkgName=%q)", fullType, gt.ImportPath, gt.PkgName)
		}
		if curImportPath != "" && gt.ImportPath == curImportPath {
			return gt.TypeName, "", nil
		}
		alias := ib.add(gt.ImportPath, gt.PkgName)
		return alias + "." + gt.TypeName, gt.ImportPath, nil
	}

	// collect used message imports (excluding current package)
	usedMsgImports := map[string]struct{}{} // importPath -> exists
	for _, s := range fd.GetService() {
		svc := s.GetName()
		if svc == "" {
			continue
		}

		b.WriteString(fmt.Sprintf("// %sSS is the SSPacket RPC interface for %s.\n", svc, svc))
		b.WriteString(fmt.Sprintf("type %sSS interface {\n", svc))
		for _, m := range s.GetMethod() {
			method := m.GetName()
			if method == "" {
				continue
			}
			inGo, imp1, err := typeRef(m.GetInputType())
			if err != nil {
				return "", err
			}
			if imp1 != "" {
				usedMsgImports[imp1] = struct{}{}
			}
			outGo, imp2, err := typeRef(m.GetOutputType())
			if err != nil {
				return "", err
			}
			if imp2 != "" {
				usedMsgImports[imp2] = struct{}{}
			}
			b.WriteString(fmt.Sprintf("\t%s(ctx *ssrpc.Context, req *%s) (*%s, error)\n", method, inGo, outGo))
		}
		b.WriteString("}\n\n")

		b.WriteString(fmt.Sprintf("type %sSServer struct {\n", svc))
		b.WriteString(fmt.Sprintf("\tImpl %sSS\n", svc))
		b.WriteString("\tMW []ssrpc.Middleware\n")
		b.WriteString("}\n\n")

		b.WriteString(fmt.Sprintf("// Register%sToTransactionMgr binds SSPacket cmd -> handler wrappers.\n", svc))
		b.WriteString(fmt.Sprintf("func Register%sToTransactionMgr(mgr transaction.ITransactionMgr, srv %sSServer) {\n", svc, svc))
		b.WriteString("\tif mgr == nil || srv.Impl == nil {\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n\n")

		for _, m := range s.GetMethod() {
			opts := m.GetOptions()
			ext, ok, err := readSsRpcOption(opts, extType, extMsgDesc)
			if err != nil {
				return "", err
			}
			if !ok {
				continue
			}
			if ext.cmd == 0 {
				return "", fmt.Errorf("ssrpc option requires cmd != 0 (service=%s method=%s)", svc, m.GetName())
			}

			cmd := ext.cmd
			cmdResp := ext.cmdResp
			if cmdResp == 0 {
				cmdResp = cmd + 1
			}
			oneWay := ext.oneWay

			inGo, imp1, err := typeRef(m.GetInputType())
			if err != nil {
				return "", err
			}
			if imp1 != "" {
				usedMsgImports[imp1] = struct{}{}
			}
			_, imp2, err := typeRef(m.GetOutputType())
			if err != nil {
				return "", err
			}
			if imp2 != "" {
				usedMsgImports[imp2] = struct{}{}
			}

			method := m.GetName()
			b.WriteString(fmt.Sprintf("\tmgr.RegisterCmd(g1_protocol.CMD(%d), func(c cmd_handler.IContext, data []byte) g1_protocol.ErrorCode {\n", cmd))
			b.WriteString(fmt.Sprintf("\t\tctx := ssrpc.WrapIContext(c, g1_protocol.CMD(%d))\n", cmd))
			b.WriteString(fmt.Sprintf("\t\treq := new(%s)\n", inGo))
			b.WriteString("\t\tif err := ctx.ParseMsg(data, req); err != nil {\n")
			b.WriteString("\t\t\tctx.Warningf(\"ssrpc parse failed err=%v\", err)\n")
			b.WriteString("\t\t\treturn g1_protocol.ErrorCode_ERR_MARSHAL\n")
			b.WriteString("\t\t}\n\n")

			// build handler + middleware chain
			b.WriteString("\t\tvar h ssrpc.Handler = func(c2 *ssrpc.Context, in proto.Message) (proto.Message, error) {\n")
			b.WriteString(fmt.Sprintf("\t\t\treturn srv.Impl.%s(c2, in.(*%s))\n", method, inGo))
			b.WriteString("\t\t}\n")
			b.WriteString("\t\tif len(srv.MW) > 0 {\n")
			b.WriteString("\t\t\th = ssrpc.Chain(srv.MW...)(h)\n")
			b.WriteString("\t\t}\n")
			b.WriteString("\t\trspAny, err := h(ctx, req)\n")
			b.WriteString("\t\tif err != nil {\n")
			b.WriteString("\t\t\treturn ssrpc.ToErrorCode(err)\n")
			b.WriteString("\t\t}\n")
			if oneWay {
				b.WriteString("\t\t_ = rspAny\n")
				b.WriteString("\t\treturn g1_protocol.ErrorCode_ERR_OK\n")
			} else {
				b.WriteString(fmt.Sprintf("\t\tif rspAny != nil {\n\t\t\tssrpc.SendMsgBackWithCmd(ctx.IContext, g1_protocol.CMD(%d), rspAny)\n\t\t}\n", cmdResp))
				b.WriteString("\t\treturn g1_protocol.ErrorCode_ERR_OK\n")
			}
			b.WriteString("\t})\n\n")
		}

		b.WriteString("}\n\n")
	}

	// Now prepend import block after collecting all imports.
	// NOTE: we build import block here and inject it after package declaration.
	// Because we already wrote content to builder, we do a simple rewrite.
	content := b.String()

	// construct final import list
	imports := []importSpec{
		{Path: "github.com/Iori372552686/GoOne/lib/api/cmd_handler", Alias: ""},
		{Path: "github.com/Iori372552686/GoOne/lib/service/ssrpc", Alias: ""},
		{Path: "github.com/Iori372552686/GoOne/lib/service/transaction", Alias: ""},
		{Path: "github.com/Iori372552686/game_protocol/protocol", Alias: "g1_protocol"},
		{Path: "github.com/golang/protobuf/proto", Alias: ""},
	}
	// deterministic import order
	extra := make([]string, 0, len(usedMsgImports))
	for impPath := range usedMsgImports {
		extra = append(extra, impPath)
	}
	sort.Strings(extra)
	for _, impPath := range extra {
		alias := ib.byPath[impPath]
		if alias == "" {
			alias = ib.add(impPath, filepath.Base(impPath))
		}
		imports = append(imports, importSpec{Path: impPath, Alias: alias})
	}

	var iblk strings.Builder
	iblk.WriteString("import (\n")
	for _, im := range imports {
		if im.Alias != "" {
			iblk.WriteString(fmt.Sprintf("\t%s \"%s\"\n", im.Alias, im.Path))
		} else {
			iblk.WriteString(fmt.Sprintf("\t\"%s\"\n", im.Path))
		}
	}
	iblk.WriteString(")\n\n")

	// inject import block after "package xxx\n\n"
	pkgDecl := "package " + goPkgName + "\n\n"
	if !strings.Contains(content, pkgDecl) {
		return "", fmt.Errorf("internal: cannot find package decl to inject imports")
	}
	content = strings.Replace(content, pkgDecl, pkgDecl+iblk.String(), 1)

	return content, nil
}

type ssrpcOpt struct {
	cmd     uint32
	cmdResp uint32
	oneWay  bool
	uidLock bool
	comment string
}

func buildSsRpcExtension(fds []*descriptorpb.FileDescriptorProto) (protoreflect.ExtensionType, protoreflect.MessageDescriptor, error) {
	set := &descriptorpb.FileDescriptorSet{File: fds}
	files, err := protodesc.NewFiles(set)
	if err != nil {
		return nil, nil, err
	}

	// locate extension descriptor by full name (best-effort).
	var extDesc protoreflect.ExtensionDescriptor
	files.RangeFiles(func(fd protoreflect.FileDescriptor) bool {
		exts := fd.Extensions()
		for i := 0; i < exts.Len(); i++ {
			e := exts.Get(i)
			if string(e.FullName()) == ssrpcExtFullName {
				extDesc = e
				return false
			}
		}
		return true
	})

	if extDesc == nil {
		// fallback: try to locate by known file path + name.
		if fd, err2 := files.FindFileByPath(ssrpcOptFilePath); err2 == nil {
			extDesc = fd.Extensions().ByName("ssrpc")
		}
	}
	if extDesc == nil {
		return nil, nil, fmt.Errorf("cannot find ssrpc extension %q (did you import %q?)", ssrpcExtFullName, ssrpcOptFilePath)
	}

	extType := dynamicpb.NewExtensionType(extDesc)
	msgDesc := extDesc.Message()
	if msgDesc == nil {
		return nil, nil, errors.New("ssrpc extension is not a message type")
	}
	return extType, msgDesc, nil
}

func readSsRpcOption(opts *descriptorpb.MethodOptions, extType protoreflect.ExtensionType, extMsgDesc protoreflect.MessageDescriptor) (ssrpcOpt, bool, error) {
	if opts == nil {
		return ssrpcOpt{}, false, nil
	}
	if !proto.HasExtension(opts, extType) {
		return ssrpcOpt{}, false, nil
	}
	v := proto.GetExtension(opts, extType)
	pm, ok := v.(proto.Message)
	if !ok || pm == nil {
		return ssrpcOpt{}, true, fmt.Errorf("ssrpc extension value type mismatch: %T", v)
	}
	m := pm.ProtoReflect()
	// cmd
	cmd := getUint32(m, extMsgDesc.Fields().ByName("cmd"))
	cmdResp := getUint32(m, extMsgDesc.Fields().ByName("cmd_resp"))
	oneWay := getBool(m, extMsgDesc.Fields().ByName("one_way"))
	uidLock := getBool(m, extMsgDesc.Fields().ByName("uid_lock"))
	comment := getString(m, extMsgDesc.Fields().ByName("comment"))

	return ssrpcOpt{cmd: cmd, cmdResp: cmdResp, oneWay: oneWay, uidLock: uidLock, comment: comment}, true, nil
}

func getUint32(m protoreflect.Message, fd protoreflect.FieldDescriptor) uint32 {
	if fd == nil {
		return 0
	}
	if !m.Has(fd) {
		return 0
	}
	return uint32(m.Get(fd).Uint())
}

func getBool(m protoreflect.Message, fd protoreflect.FieldDescriptor) bool {
	if fd == nil {
		return false
	}
	if !m.Has(fd) {
		return false
	}
	return m.Get(fd).Bool()
}

func getString(m protoreflect.Message, fd protoreflect.FieldDescriptor) string {
	if fd == nil {
		return ""
	}
	if !m.Has(fd) {
		return ""
	}
	return m.Get(fd).String()
}

func goTypeNameFromProtoType(filePkg string, fullType string) (string, error) {
	// fullType: ".pkg.Msg" or ".pkg.Outer.Inner"
	fullType = strings.TrimSpace(fullType)
	fullType = strings.TrimPrefix(fullType, ".")
	if fullType == "" {
		return "", fmt.Errorf("empty proto type")
	}
	parts := strings.Split(fullType, ".")
	filePkgParts := strings.Split(filePkg, ".")
	if len(parts) <= len(filePkgParts) {
		return "", fmt.Errorf("invalid proto type %q for file package %q", fullType, filePkg)
	}
	// Phase A: expect input/output messages in the same proto package.
	for i := 0; i < len(filePkgParts); i++ {
		if parts[i] != filePkgParts[i] {
			return "", fmt.Errorf("cross-package message not supported yet (filePkg=%q type=%q)", filePkg, fullType)
		}
	}
	msgParts := parts[len(filePkgParts):]
	// Protoc-gen-go maps nested messages to Outer_Inner.
	return strings.Join(msgParts, "_"), nil
}

func guessGoPkgName(goPackageOpt string, protoPkg string) string {
	// go_package format: "path/to/pkg;name"
	if goPackageOpt != "" {
		if i := strings.LastIndex(goPackageOpt, ";"); i >= 0 && i+1 < len(goPackageOpt) {
			return sanitizeGoIdent(goPackageOpt[i+1:])
		}
		base := filepath.Base(goPackageOpt)
		if base != "" && base != "." && base != "/" {
			return sanitizeGoIdent(base)
		}
	}

	// proto package: a.b.c -> c
	if protoPkg != "" {
		parts := strings.Split(protoPkg, ".")
		return sanitizeGoIdent(parts[len(parts)-1])
	}
	return "gen"
}

func sanitizeGoIdent(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "gen"
	}
	// minimal sanitize: replace '-' with '_'
	s = strings.ReplaceAll(s, "-", "_")
	return s
}
